name: test
on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: runit
        id: runit
        uses: ./action
        with:
          name: 'Jesse'

      - run: echo "The time was ${{ steps.runit.outputs.time }}"

  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run composite
        id: run-composite
        uses: ./composite
        with:
          name: 'Jesse-Composite'
          
      - run: echo "The time was ${{ steps.run-composite-outputs.time }}"
